# Jekyll configuration
title: CNC Pigment Blog
email: your-email@example.com
description: >-
  A blog about CNC Pigment and related projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ericu.be" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  ericubey

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
